### ISSUE TITLE
Link in README gives 404

### ISSUE THREAD

**Issue by andrechalom** [kblake/neural-network#2]
The link in the README file reads "neural_network", but the path in GitHub is "neural-network". This may seem unimportant for people arriving here via GitHub, but it's hard to find the right repository coming from rubydoc.

**Comment by andrechalom** [comment]
Also: the link for the Contributor Covenant is being treated as a local file

**Comment by kblake** [comment]
Excellent catch! Fixed both issues.

Thanks!
